# Generated by Django 3.2.7 on 2021-11-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmls',
            name='cnpj',
            field=models.CharField(max_length=255),
        ),
    ]
