# Generated by Django 3.2.7 on 2021-11-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_xmls_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmls',
            name='nomeFile',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='xmls',
            name='xml',
            field=models.CharField(max_length=20000),
        ),
    ]
