# Generated by Django 3.2.8 on 2021-11-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_xmls_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmls',
            name='xml',
            field=models.CharField(max_length=400),
        ),
    ]
