# Generated by Django 3.2.8 on 2021-11-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_xmls_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmls',
            name='xml',
            field=models.CharField(max_length=10000),
        ),
    ]
