# Generated by Django 3.2.8 on 2021-11-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211104_1628'),
        ('blog', '0005_alter_xmls_xml'),
    ]

    operations = [
    ]
