# Generated by Django 3.2.8 on 2021-11-05 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_merge_0003_auto_20211104_1628_0005_alter_xmls_xml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmls',
            name='parceiro',
        ),
    ]
